[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Patches lifted straight from Cryptid (The Tax effect), and from https://github.com/Mysthaps/LobotomyCorp
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
position = "at"
payload = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = G.GAME.blind.cap_score and G.GAME.blind:cap_score(math.floor(hand_chips*mult),true) or math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "ease_to = G.GAME.chips + math.floor(hand_chips*mult),"
position = "at"
payload = "ease_to = G.GAME.chips + (G.GAME.blind.cap_score and G.GAME.blind:cap_score(math.floor(hand_chips*mult),false) or math.floor(hand_chips*mult)),"
match_indent = true

# very confusing for some reason
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local ret = self.ability.perma_mult or 0"
position = "after"
payload = '''
if self.ability.effect == "Extra Bonus Card" then
    ret = ret + self.ability.mult
end
'''
match_indent = true